server:
  port: 9004

spring:
  application:
    name: distributed-order-service
  cloud:
    #注册中心地址
    nacos:
      discovery:
        server-addr: 8.130.44.244:8848

  #消息队列
  rabbitmq:
    host: 8.130.44.244
    port: 5672
    virtual-host: /
    password: password
    username: admin
    #开启手动确认消息
    listener:
      simple:
        acknowledge-mode: manual

#数据库配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://8.130.44.244:3306/cafe_order?allowPublicKeyRetrieval=true&useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: ds
    password: distributedsystem

#redis 配置
  redis:
    host: 8.130.44.244
    port: 8000
    password: 123456


#配置plus打印sql日志
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


feign:
  client:
    config:
      default:
        connectTimeout: 10000 # 连接超时时间（毫秒）
        readTimeout: 30000 # 读取超时时间（毫秒）

#设置日志级别,ERROR/WARN/INFO/DEBUG,默认是INFO以上才显示
logging:
  level:
    root: INFO




#自定义消息队列配置，发送锁定库存消息-》延迟exchange-》lock.queue-》死信exchange-》release.queue
mqconfig:
  #延迟队列，不能被监听消费
  order_close_delay_queue: order.close.delay.queue

  #延迟队列的消息过期后转发的队列
  order_close_queue: order.close.queue

  #交换机
  order_event_exchange: order.event.exchange

  #进入延迟队列的路由key
  order_close_delay_routing_key: order.close.delay.routing.key

  #消息过期，进入释放队列的key,进入死信队列的key
  order_close_routing_key: order.close.routing.key

  #消息过期时间,毫秒，临时改为5分钟定时关单
  ttl: 60000



#支付宝配置
alipay:
  #支付成功的跳转页面
  success_return_url: https://google.com

  #支付宝通知回调接口, 蚂蚁金服开放平台应用后台也需要配置对应的地址
  callback_url: https://google.com
