server:
  port: 9001

spring:
  application:
    name: distributed-user-service
  cloud:
    #注册中心地址
    nacos:
      discovery:
        server-addr: 8.130.44.244:8848


#数据库配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://8.130.44.244:3306/cafe_user?allowPublicKeyRetrieval=true&useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: ds
    password: distributedsystem
#redis 配置
  redis:
    host: 8.130.44.244
    port: 8000
    password: 123456

#邮箱配置
  mail:
    host: smtp.163.com #发送邮件服务器
    username: zhangzhuofan2019@163.com #发送邮件的邮箱地址
    password: LETAVMOQRWIJSILN #客户端授权码，不是邮箱密码,网易的是自己设置的
    from: zhangzhuofan2019@163.com # 发送邮件的地址，和上面username一致
    properties.mail.smtp.starttls.enable: true
    properties.mail.smtp.starttls.required: true
    properties.mail.smtp.ssl.enable: true
    default-encoding: utf-8

#配置plus打印sql日志
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
feign:
  client:
    config:
      default:
        connectTimeout: 10000 # Connection timeout in milliseconds
        readTimeout: 30000 # Read timeout in milliseconds


#设置日志级别,ERROR/WARN/INFO/DEBUG,默认是INFO以上才显示
logging:
  level:
    root: INFO


#阿里云OSS配置
aliyun:
  oss:
    endpoint: oss-cn-shenzhen.aliyuncs.com
    access-key-id: LTAI4GJR7bL8JEzBv7zx69J4
    access-key-secret: CNfxHJeTTLlFQA2a2X5BprjqjK047l
    bucketname: xdclass-1024shop-img
